-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local ROOMINFO_PB = require("RoomInfo_pb")
local RESULTINFO_PB = require("ResultInfo_pb")
module('GetRoom_pb')


local localTable = {}
GETROOMREQUEST = protobuf.Descriptor()
localTable.GETROOMREQUEST_ROOMID_FIELD = protobuf.FieldDescriptor()
GETROOMRESPONSE = protobuf.Descriptor()
localTable.GETROOMRESPONSE_RESULT_FIELD = protobuf.FieldDescriptor()
localTable.GETROOMRESPONSE_ROOM_FIELD = protobuf.FieldDescriptor()
localTable.GETROOMRESPONSE_MESSAGE_FIELD = protobuf.FieldDescriptor()


localTable.GETROOMREQUEST_ROOMID_FIELD.name = "roomId"
localTable.GETROOMREQUEST_ROOMID_FIELD.full_name = ".com.gameroot.lg.message.GetRoomRequest.roomId"
localTable.GETROOMREQUEST_ROOMID_FIELD.number = 1
localTable.GETROOMREQUEST_ROOMID_FIELD.index = 0
localTable.GETROOMREQUEST_ROOMID_FIELD.label = 3
localTable.GETROOMREQUEST_ROOMID_FIELD.has_default_value = false
localTable.GETROOMREQUEST_ROOMID_FIELD.default_value = {}
localTable.GETROOMREQUEST_ROOMID_FIELD.type = 5
localTable.GETROOMREQUEST_ROOMID_FIELD.cpp_type = 1

GETROOMREQUEST.name = "GetRoomRequest"
GETROOMREQUEST.full_name = ".com.gameroot.lg.message.GetRoomRequest"
GETROOMREQUEST.nested_types = {}
GETROOMREQUEST.enum_types = {}
GETROOMREQUEST.fields = {localTable.GETROOMREQUEST_ROOMID_FIELD}
GETROOMREQUEST.is_extendable = false
GETROOMREQUEST.extensions = {}
localTable.GETROOMRESPONSE_RESULT_FIELD.name = "result"
localTable.GETROOMRESPONSE_RESULT_FIELD.full_name = ".com.gameroot.lg.message.GetRoomResponse.result"
localTable.GETROOMRESPONSE_RESULT_FIELD.number = 1
localTable.GETROOMRESPONSE_RESULT_FIELD.index = 0
localTable.GETROOMRESPONSE_RESULT_FIELD.label = 2
localTable.GETROOMRESPONSE_RESULT_FIELD.has_default_value = false
localTable.GETROOMRESPONSE_RESULT_FIELD.default_value = nil
localTable.GETROOMRESPONSE_RESULT_FIELD.enum_type = RESULTINFO_PB.RESULT
localTable.GETROOMRESPONSE_RESULT_FIELD.type = 14
localTable.GETROOMRESPONSE_RESULT_FIELD.cpp_type = 8

localTable.GETROOMRESPONSE_ROOM_FIELD.name = "room"
localTable.GETROOMRESPONSE_ROOM_FIELD.full_name = ".com.gameroot.lg.message.GetRoomResponse.room"
localTable.GETROOMRESPONSE_ROOM_FIELD.number = 2
localTable.GETROOMRESPONSE_ROOM_FIELD.index = 1
localTable.GETROOMRESPONSE_ROOM_FIELD.label = 3
localTable.GETROOMRESPONSE_ROOM_FIELD.has_default_value = false
localTable.GETROOMRESPONSE_ROOM_FIELD.default_value = {}
localTable.GETROOMRESPONSE_ROOM_FIELD.message_type = ROOMINFO_PB.ROOM
localTable.GETROOMRESPONSE_ROOM_FIELD.type = 11
localTable.GETROOMRESPONSE_ROOM_FIELD.cpp_type = 10

localTable.GETROOMRESPONSE_MESSAGE_FIELD.name = "message"
localTable.GETROOMRESPONSE_MESSAGE_FIELD.full_name = ".com.gameroot.lg.message.GetRoomResponse.message"
localTable.GETROOMRESPONSE_MESSAGE_FIELD.number = 3
localTable.GETROOMRESPONSE_MESSAGE_FIELD.index = 2
localTable.GETROOMRESPONSE_MESSAGE_FIELD.label = 1
localTable.GETROOMRESPONSE_MESSAGE_FIELD.has_default_value = true
localTable.GETROOMRESPONSE_MESSAGE_FIELD.default_value = ""
localTable.GETROOMRESPONSE_MESSAGE_FIELD.type = 9
localTable.GETROOMRESPONSE_MESSAGE_FIELD.cpp_type = 9

GETROOMRESPONSE.name = "GetRoomResponse"
GETROOMRESPONSE.full_name = ".com.gameroot.lg.message.GetRoomResponse"
GETROOMRESPONSE.nested_types = {}
GETROOMRESPONSE.enum_types = {}
GETROOMRESPONSE.fields = {localTable.GETROOMRESPONSE_RESULT_FIELD, localTable.GETROOMRESPONSE_ROOM_FIELD, localTable.GETROOMRESPONSE_MESSAGE_FIELD}
GETROOMRESPONSE.is_extendable = false
GETROOMRESPONSE.extensions = {}

GetRoomRequest = protobuf.Message(GETROOMREQUEST)
GetRoomResponse = protobuf.Message(GETROOMRESPONSE)

