-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('ResultInfo_pb')


local localTable = {}
localTable.RESULT = protobuf.EnumDescriptor()
localTable.RESULT_SUCCESS_ENUM = protobuf.EnumValueDescriptor()
localTable.RESULT_FAILURE_ENUM = protobuf.EnumValueDescriptor()
localTable.RESULT_NO_RIGHT_ENUM = protobuf.EnumValueDescriptor()
localTable.RESULT_BASEDATA_NOT_FOUND_ENUM = protobuf.EnumValueDescriptor()

SUCCESS = 0
FAILURE = -1
NO_RIGHT = -2
BASEDATA_NOT_FOUND = -3

localTable.RESULT_SUCCESS_ENUM.name = "SUCCESS"
localTable.RESULT_SUCCESS_ENUM.index = 0
localTable.RESULT_SUCCESS_ENUM.number = 0
localTable.RESULT_FAILURE_ENUM.name = "FAILURE"
localTable.RESULT_FAILURE_ENUM.index = 1
localTable.RESULT_FAILURE_ENUM.number = -1
localTable.RESULT_NO_RIGHT_ENUM.name = "NO_RIGHT"
localTable.RESULT_NO_RIGHT_ENUM.index = 2
localTable.RESULT_NO_RIGHT_ENUM.number = -2
localTable.RESULT_BASEDATA_NOT_FOUND_ENUM.name = "BASEDATA_NOT_FOUND"
localTable.RESULT_BASEDATA_NOT_FOUND_ENUM.index = 3
localTable.RESULT_BASEDATA_NOT_FOUND_ENUM.number = -3
localTable.RESULT.name = "Result"
localTable.RESULT.full_name = ".com.gameroot.lg.message.Result"
localTable.RESULT.values = {localTable.RESULT_SUCCESS_ENUM,localTable.RESULT_FAILURE_ENUM,localTable.RESULT_NO_RIGHT_ENUM,localTable.RESULT_BASEDATA_NOT_FOUND_ENUM}


